server:
  port: ${PORT:5000}

base-url: /api

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

springdoc:
  swagger-ui:
    path: /swagger.html